### ISSUE TITLE
Instantaneous Heart Rate

### ISSUE THREAD

**Issue by MounikaVanka** [MounikaVanka/bme590hrm#4]
Hey Palmeri,

We wanted to know what the instantaneous heart rate meant?
Since we need a window to get the heart rate right?

**Comment by mlp6** [comment]
"Instantaneous" is one of the ambiguous terms.  Like your comment mentions, you will need to work over some sort of finite temporal window to make your heart rate estimates... it would be good to have those parameters be inputs to your functions that you can modulate to test against data for being more accurate, robust, etc.

**Comment by MounikaVanka** [comment]
Sounds good! Thanks
